// Generated by CoffeeScript 1.6.2
/*

Author   : Caoxingming
Email    : simeon.chaos@gmail.com
Homepage : https://github.com/chaosim
Source   : https://github.com/chaosim/nodejs_utils
License  : Simplified BSD License
Version  : 0.1.0

Copyright 2013 Caoxingming. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY CAOXINGMING 'AS IS' AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
EVENT SHALL CAOXINGMING OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The views and conclusions contained in the software and documentation are those
of the authors and should not be interpreted as representing official policies,
either expressed or implied, of Caoxingmingi.
*/


/*
# usage: copy this file to your project and then:

# javascript:
new Set(data)
set(data)
  method: add, remove, keys, union, has.

# SEE test/test_set.js for more information

# in coffeescript:

new Set(data)
set(data)

method: add, remove, keys, union, has.

# SEE test/test_set.coffee for more information
*/


(function() {
  var Set, _,
    __slice = [].slice;

  _ = require("underscore");

  Set = exports.Set = (function() {
    function Set(data) {
      var x, _i, _len;

      if (_.isString(data) || _.isArray(data)) {
        this.data = {};
        for (_i = 0, _len = data.length; _i < _len; _i++) {
          x = data[_i];
          this.data[x] = true;
        }
      } else {
        this.data = data || {};
      }
    }

    Set.prototype.add = function(key) {
      return this.data[key] = true;
    };

    Set.prototype.remove = function(key) {
      return delete this.data[key];
    };

    Set.prototype.has = function(key) {
      return this.data.hasOwnProperty(key);
    };

    Set.prototype.isEmpty = function() {
      var key;

      for (key in this.data) {
        if (this.data.hasOwnProperty(key)) {
          return false;
        }
      }
      return true;
    };

    Set.prototype.keys = function() {
      var k, _results;

      _results = [];
      for (k in this.data) {
        _results.push(k);
      }
      return _results;
    };

    Set.prototype.clear = function() {
      return this.data = {};
    };

    Set.prototype.union = function(other) {
      var result, x, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;

      result = new Set();
      _ref = this.keys();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        x = _ref[_i];
        result.add(x);
      }
      if (_.isString(other) || _.isArray(other)) {
        for (_j = 0, _len1 = other.length; _j < _len1; _j++) {
          x = other[_j];
          result.add(x);
        }
      } else if (other instanceof Set) {
        _ref1 = other.keys();
        for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
          x = _ref1[_k];
          result.add(x);
        }
      } else {
        for (x in other) {
          result.add(x);
        }
      }
      return result;
    };

    Set.prototype.unionAt = function(other) {
      var x, _i, _j, _len, _len1, _ref;

      if (_.isString(other) || _.isArray(other)) {
        for (_i = 0, _len = other.length; _i < _len; _i++) {
          x = other[_i];
          this.add(x);
        }
      } else if (other instanceof Set) {
        _ref = other.keys();
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          x = _ref[_j];
          this.add(x);
        }
      } else {
        for (x in other) {
          this.add(x);
        }
      }
      return this;
    };

    Set.prototype.copy = function() {
      return new Set(this.keys());
    };

    Set.prototype.merge = function() {
      var containers, result, x, _i, _len;

      containers = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      result = this.copy();
      for (_i = 0, _len = containers.length; _i < _len; _i++) {
        x = containers[_i];
        result = result.union(x);
      }
      return result;
    };

    Set.prototype.mergeAt = function() {
      var containers, x, _i, _len;

      containers = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      for (_i = 0, _len = containers.length; _i < _len; _i++) {
        x = containers[_i];
        this.unionAt(x);
      }
      return this;
    };

    return Set;

  })();

  exports.set = function(data) {
    return new Set(data);
  };

}).call(this);

/*
//@ sourceMappingURL=set.map
*/
